# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:1Yrvfk2rwXKrTquUF2vZy3HB1fKvJg3nQiXl9r2R4/8TdQ==,iv:bg+wylcyLt7exL/CkP/QwVvqXPBn84ON7HSRZ5hKo1o=,tag:GbG7g7veYgdUVNbVIO3GKw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:eeteiKfEtlGPrtyE0FHBUUV/R/n4wNRzwLXprhKSVi8q0UXDRQ==,iv:shyb/pvORvIBRDihSnsEZt2l/MgAU4HKEHVx+K4yBas=,tag:igcsvkFjsNQ3ee99/HYnYw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:ZswkoEZwukY7rnjoYUU2/HY=,iv:OFM3BPcpHIPtnOwKwGPtrvj5K7wU77J8i3vLmCtS+/8=,tag:k71KzfWehgyrhN9BSnOHyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16lj2h06nskdtp8s9942awnuv7vgnqe242ljxnj6cq2zsg5utmpjqxpqjgu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZVhDeEhSdVc2MTVaaWRl
            SnE0bURLYmdzTkpxTFp2NkJaZzJoUTF6T2lJCkxFMmpYS3V0OXFGaDhZL2FuVkNY
            T2pMRURkUXdUcVd3bkE2Zm1nZ2Q3SjAKLS0tIG5la2NmL3dJMlMvTDJ4a1BEeCtZ
            b1lydGN3TnYvR0ZPais2VUg1dDhUMDAKhlTfWsOhLIrSnENtxdFAfq/xW6wRdMj9
            EAq3ok5T9dCbHhDjLqzAFm69sxvuG0LHJihHpi3OHp8omf+sDLDFzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-29T03:02:52Z"
    mac: ENC[AES256_GCM,data:2+UDQBm2Gs8A/FW1/70blKdbzPPs1ko85tVkQwI6MAqxk9mxMUzZ4oNVBFeGHHK27yQAmV7eS30MsuONEXcH4JWBlUeD2t85BSxnELS34wuF/O5+WY79kNZEeN+53VtvwqzsjULPYGtPU6rw3gqglKyh1Zkn03IUS8fX94/yvFo=,iv:NmIFlwjGY43XCMNBePB1SFrjvSIrW/CGrIjeLn1iWBc=,tag:gr1tPb6i1A6Q4bG/OkThgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
