---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Denver
  METALLB_LB_RANGE: 192.168.9.120-192.168.9.130
  METALLB_K8S_GATEWAY_ADDR: 192.168.9.130
  METALLB_INGRESS_ADDR: 192.168.9.129
